# A biblioteca dijkstar, adiciona a função Graph, a função find_path e a função graph.add_edge([nó A], [nó B], [peso])

from dijkstar import Graph, find_path 

# Definindo o grafo como um dicionário de adjacência
# graph = Graph()
# graph.add_edge(1, 3, 2)
# graph.add_edge(3, 4, 4)
# graph.add_edge(4, 6, 10)
# graph.add_edge(4, 7, 1)
# graph.add_edge(1, 7, 3)

 # Chamando a função dijkstra
# shortest_path = find_path(graph, 1, 7)

 # Exibindo os resultados
# print(graph)
# print(shortest_path)


# Linha 8-Diamante
graph.add_edge("Júlio Prestes", "Palmeiras-Barra Funda", 1)
graph.add_edge("Palmeiras-Barra Funda", "Júlio Prestes", 1)
graph.add_edge("Palmeiras-Barra Funda", "Lapa", 1)
graph.add_edge("Lapa", "Palmeiras-Barra Funda", 1)
graph.add_edge("Lapa", "Domingos de Moraes", 1)
graph.add_edge("Domingos de Moraes", "Lapa", 1)
graph.add_edge("Domingos de Moraes", "Imperatriz Leopoldina", 1)
graph.add_edge("Imperatriz Leopoldina", "Domingos de Moraes", 1)
graph.add_edge("Imperatriz Leopoldina", "Presidente Altino", 1)
graph.add_edge("Presidente Altino", "Imperatriz Leopoldina", 1)
graph.add_edge("Presidente Altino", "Osasco", 1)
graph.add_edge("Osasco", "Presidente Altino", 1)
graph.add_edge("Osasco", "Comandante Sampaio", 1)
graph.add_edge("Comandante Sampaio", "Osasco", 1)
graph.add_edge("Comandante Sampaio", "Quitaúna", 1)
graph.add_edge("Quitaúna", "Comandante Sampaio", 1)
graph.add_edge("Quitaúna", "General Miguel Costa", 1)
graph.add_edge("General Miguel Costa", "Quitaúna", 1)
graph.add_edge("General Miguel Costa", "Carapicuíba", 1)
graph.add_edge("Carapicuíba", "General Miguel Costa", 1)
graph.add_edge("Carapicuíba", "Santa Terezinha", 1)
graph.add_edge("Santa Terezinha", "Carapicuíba", 1)
graph.add_edge("Santa Terezinha", "Antonio João", 1)
graph.add_edge("Antonio João", "Santa Terezinha", 1)
graph.add_edge("Antonio João", "Barueri", 1)
graph.add_edge("Barueri", "Antonio João", 1)
graph.add_edge("Barueri", "Jardim Belval", 1)
graph.add_edge("Jardim Belval", "Barueri", 1)
graph.add_edge("Jardim Belval", "Jardim Silveira", 1)
graph.add_edge("Jardim Silveira", "Jardim Belval", 1)
graph.add_edge("Jardim Silveira", "Jandira", 1)
graph.add_edge("Jandira", "Jardim Silveira", 1)
graph.add_edge("Jandira", "Sagrado Coração", 1)
graph.add_edge("Sagrado Coração", "Jandira", 1)
graph.add_edge("Sagrado Coração", "Engenheiro Cardoso", 1)
graph.add_edge("Engenheiro Cardoso", "Sagrado Coração", 1)
graph.add_edge("Engenheiro Cardoso", "Itapevi", 1)
graph.add_edge("Itapevi", "Engenheiro Cardoso", 1)
graph.add_edge("Itapevi", "Amador Bueno", 1)
graph.add_edge("Amador Bueno", "Itapevi", 1)


# Linha 9-Esmeralda
graph.add_edge("Ceasa", "Presidente Altino", 1)
graph.add_edge("Presidente Altino", "Ceasa", 1)
graph.add_edge("Ceasa", "Villa-Lobos - Jaguaré", 1)
graph.add_edge("Villa-Lobos - Jaguaré", "Ceasa", 1)
graph.add_edge("Villa-Lobos - Jaguaré", "Cidade Universitária", 1)
graph.add_edge("Cidade Universitária", "Villa-Lobos - Jaguaré", 1)
graph.add_edge("Cidade Universitária", "Pinheiros", 1)
graph.add_edge("Pinheiros", "Cidade Universitária", 1)
graph.add_edge("Pinheiros", "Hebraica-Rebouças", 1)
graph.add_edge("Hebraica-Rebouças", "Pinheiros", 1)
graph.add_edge("Pinheiros", "Faria Lima", 1)
graph.add_edge("Faria Lima", "Pinheiros", 1)
graph.add_edge("Hebraica-Rebouças", "Cidade Jardim", 1)
graph.add_edge("Cidade Jardim", "Hebraica-Rebouças", 1)
graph.add_edge("Cidade Jardim", "Vila Olímpia", 1)
graph.add_edge("Vila Olímpia", "Cidade Jardim", 1)
graph.add_edge("Vila Olímpia", "Berrini", 1)
graph.add_edge("Berrini", "Vila Olímpia", 1)
graph.add_edge("Berrini", "Morumbi", 1)
graph.add_edge("Morumbi", "Berrini", 1)
graph.add_edge("Morumbi", "Granja Julieta", 1)
graph.add_edge("Granja Julieta", "Morumbi", 1)
graph.add_edge("Granja Julieta", "Santo Amaro", 1)
graph.add_edge("Santo Amaro", "Granja Julieta", 1)
graph.add_edge("Santo Amaro", "Socorro", 1)
graph.add_edge("Socorro", "Santo Amaro", 1)
graph.add_edge("Socorro", "Jurubatuba", 1)
graph.add_edge("Jurubatuba", "Socorro", 1)
graph.add_edge("Jurubatuba", "Autódromo", 1)
graph.add_edge("Autódromo", "Jurubatuba", 1)
graph.add_edge("Autódromo", "Interlagos", 1)
graph.add_edge("Interlagos", "Autódromo", 1)
graph.add_edge("Interlagos", "Grajaú", 1)
graph.add_edge("Grajaú", "Interlagos", 1)
graph.add_edge("Grajaú", "Mendes-Vila Natal", 1)
graph.add_edge("Mendes-Vila Natal", "Grajaú", 1)


# Linha 1-Azul
graph.add_edge("Jabaquara", "Conceição", 1)
graph.add_edge("Conceição", "Jabaquara", 1)
graph.add_edge("Conceição", "São Judas", 1)
graph.add_edge("São Judas", "Conceição", 1)
graph.add_edge("São Judas", "Saúde", 1)
graph.add_edge("Saúde", "São Judas", 1)
graph.add_edge("Saúde", "Praça da Árvore", 1)
graph.add_edge("Praça da Árvore", "Saúde", 1)
graph.add_edge("Praça da Árvore", "Santa Cruz", 1)
graph.add_edge("Santa Cruz", "Praça da Árvore", 1)
graph.add_edge("Santa Cruz", "Vila Mariana", 1)
graph.add_edge("Vila Mariana", "Santa Cruz", 1)
graph.add_edge("Vila Mariana", "Ana Rosa", 1)
graph.add_edge("Ana Rosa", "Vila Mariana", 1)
graph.add_edge("Ana Rosa", "Paraíso", 1)
graph.add_edge("Paraíso", "Ana Rosa", 1)
graph.add_edge("Paraíso", "Vergueiro", 1)
graph.add_edge("Vergueiro", "Paraíso", 1)
graph.add_edge("Vergueiro", "São Joaquim", 1)
graph.add_edge("São Joaquim", "Vergueiro", 1)
graph.add_edge("São Joaquim", "Liberdade", 1)
graph.add_edge("Liberdade", "São Joaquim", 1)
graph.add_edge("Liberdade", "Sé", 1)
graph.add_edge("Sé", "Liberdade", 1)
graph.add_edge("Sé", "São Bento", 1)
graph.add_edge("São Bento", "Sé", 1)
graph.add_edge("São Bento", "Luz", 1)
graph.add_edge("Luz", "São Bento", 1)
graph.add_edge("Luz", "Tiradentes", 1)
graph.add_edge("Tiradentes", "Luz", 1)
graph.add_edge("Tiradentes", "Armênia", 1)
graph.add_edge("Armênia", "Tiradentes", 1)
graph.add_edge("Armênia", "Portuguesa-Tietê", 1)
graph.add_edge("Portuguesa-Tietê", "Armênia", 1)
graph.add_edge("Portuguesa-Tietê", "Carandiru", 1)
graph.add_edge("Carandiru", "Portuguesa-Tietê", 1)
graph.add_edge("Carandiru", "Santana", 1)
graph.add_edge("Santana", "Carandiru", 1)
graph.add_edge("Santana", "Jardim São Paulo-Ayrton Senna", 1)
graph.add_edge("Jardim São Paulo-Ayrton Senna", "Santana", 1)
graph.add_edge("Jardim São Paulo-Ayrton Senna", "Parada Inglesa", 1)
graph.add_edge("Parada Inglesa", "Jardim São Paulo-Ayrton Senna", 1)
graph.add_edge("Parada Inglesa", "Tucuruvi", 1)
graph.add_edge("Tucuruvi", "Parada Inglesa", 1)


# Linha 2-Verde
graph.add_edge("Vila Madalena", "Santuário Nossa Senhora de Fátima-Sumaré", 1)
graph.add_edge("Santuário Nossa Senhora de Fátima-Sumaré", "Vila Madalena", 1)
graph.add_edge("Santuário Nossa Senhora de Fátima-Sumaré", "Clínicas", 1)
graph.add_edge("Clínicas", "Santuário Nossa Senhora de Fátima-Sumaré", 1)
graph.add_edge("Clínicas", "Consolação", 1)
graph.add_edge("Consolação", "Clínicas", 1)
graph.add_edge("Consolação", "Trianon-Masp", 1)
graph.add_edge("Trianon-Masp", "Consolação", 1)
graph.add_edge("Trianon-Masp", "Brigadeiro", 1)
graph.add_edge("Brigadeiro", "Trianon-Masp", 1)
graph.add_edge("Brigadeiro", "Paraíso", 1)
graph.add_edge("Paraíso", "Brigadeiro", 1)
graph.add_edge("Ana Rosa", "Paraíso", 1)
graph.add_edge("Paraíso", "Ana Rosa", 1)
graph.add_edge("Ana Rosa", "Chácara Klabin", 1)
graph.add_edge("Chácara Klabin", "Ana Rosa", 1)
graph.add_edge("Chácara Klabin", "Santos-Imigrantes", 1)
graph.add_edge("Santos-Imigrantes", "Chácara Klabin", 1)
graph.add_edge("Santos-Imigrantes", "Alto do Ipiranga", 1)
graph.add_edge("Alto do Ipiranga", "Santos-Imigrantes", 1)
graph.add_edge("Alto do Ipiranga", "Sacomã", 1)
graph.add_edge("Sacomã", "Alto do Ipiranga", 1)
graph.add_edge("Sacomã", "Tamanduateí", 1)
graph.add_edge("Tamanduateí", "Sacomã", 1)
graph.add_edge("Tamanduateí", "Vila Prudente", 1)
graph.add_edge("Vila Prudente", "Tamanduateí", 1)


# Linha 4-Amarela
graph.add_edge("República", "Luz", 1)
graph.add_edge("Luz", "República", 1)
graph.add_edge("República", "Higienópolis-Mackenzie", 1)
graph.add_edge("Higienópolis-Mackenzie", "República", 1)
graph.add_edge("Higienópolis-Mackenzie", "Paulista", 1)
graph.add_edge("Paulista", "Higienópolis-Mackenzie", 1)
graph.add_edge("Paulista", "Oscar Freire", 1)
graph.add_edge("Oscar Freire", "Paulista", 1)
graph.add_edge("Oscar Freire", "Fradinho Coutinho", 1)
graph.add_edge("Fradinho Coutinho", "Oscar Freire", 1)
graph.add_edge("Fradinho Coutinho", "Faria Lima", 1)
graph.add_edge("Faria Lima", "Fradinho Coutinho", 1)
graph.add_edge("Faria Lima", "Pinheiros", 1)
graph.add_edge("Pinheiros", "Faria Lima", 1)
graph.add_edge("Butantã", "Pinheiros", 1)
graph.add_edge("Pinheiros", "Butantã", 1)
graph.add_edge("Butantã", "São Paulo-Morumbi", 1)
graph.add_edge("São Paulo-Morumbi", "Butantã", 1)
graph.add_edge("São Paulo-Morumbi", "Vila Sônia", 1)
graph.add_edge("Vila Sônia", "São Paulo-Morumbi", 1)

